name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: action/checkout@v3 
        with: 
          path: react-app 
          ref: ${{ github.event.pull_request.head.sha }}
      - name: 
